[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
variables = { FLASK_ENV = "production", PORT = "5000", RAILWAY_TOKEN = "6ce3ddc0-6d5c-41c8-9c16-dac5ba47b7a9" }

[environments.staging]
variables = { FLASK_ENV = "staging", PORT = "5000" }

# Service configuration
[[services]]
name = "signalwire-webhook"
source = "."

[services.build]
watchPatterns = ["**/*.py", "requirements.txt"]

[services.deploy]
numReplicas = 1
healthcheckPath = "/health" 